
const productDetails = [
  {
    fashion: [
      {
        name: "Linen Screen Print Fashionable Long Gown For Women - Black - G-N05",
        image: "/assets/fashion/PHOTO-2024-11-15-08-51-26.jpg",
        price: "2000",
        discount_price: "1500",
      },
      {
        name: "Linen Screen Print Fashionable Long Gown For Women - White - G-N08",
        image: "/assets/fashion/PHOTO-2024-11-15-08-52-56.jpg",
        price: "2000",
        discount_price: "1500",
      },
      {
        name: "Linen Screen Print Fashionable Long low - G-N03Gown For Women - Yel",
        image: "/assets/fashion/PHOTO-2024-11-15-08-53-56.jpg",
        price: "2000",
        discount_price: "1500",
      },
      {
        name: "Georgette Double Shrug For Women - Maroon",
        image: "/assets/fashion/PHOTO-2024-11-15-08-54-53.jpg",
        price: "2000",
        discount_price: "1500",
      },
      {
        name: "Georgette Double Shrug For Women - Light Mauve",
        image: "/assets/fashion/PHOTO-2024-11-15-08-55-59.jpg",
        price: "2000",
        discount_price: "1500",
      },
      {
        name: "Half Silk Hand Print Sharee For Women - Purple",
        image: "/assets/fashion/PHOTO-2024-11-15-08-59-26.jpg",
        price: "1290",
        discount_price: "944",
      },
      {
        name: "Hand Print Couple Set Saree With Panjabi - Blue - CS-75",
        image: "/assets/fashion/PHOTO-2024-11-15-08-59-26.jpg",
        price: "2150",
        discount_price: "1243",
      },
      {
        name: "Hand Print Couple Set Saree With Panjabi - White And Green - CS-65",
        image: "/assets/fashion/PHOTO-2024-11-15-09-00-41.jpg",
        price: "2150",
        discount_price: "1243",
      },
      {
        name: "Full Sleeve Premium Hoodie for Men Sweatshirt ",
        image: "/assets/fashion/PHOTO-2024-11-15-09-05-07.jpg",
        price: "850",
        discount_price: "380",
      },
    ],
    mobiles: [
      {
        name: "Geo R11 Feature Phone",
        image: "/assets/phone/PHOTO-2024-11-14-22-03-26.jpg",
        price: "2700",
        discount_price: "2350",
        specification: "",
        brand: "GEO PHONE",
        model: "",
        usb: "",
        bluetooth_dialer: "",
        fm_recording: "",
        display: "1.44 Inch Display",
        sim_slot: "2",
        dedicated_power_key: "Yes",
        dedicated_reset_key: "Yes",
        screen: "2.5D",
        processor: `MTK6261D`,
        camera: "0.3MP",
        battery: "1000mAh Integrated",
        phonebook_memory: "1000 contacts",
        warranty: "1 Year",
        description: ` Touch Keypad,1.44 Inch Display,2.5D Screen, MTK6261D Processor,0.3MP Camera, 
                    Wireless FM, Bluetooth Dialer, Strong Metal Sensation, 1000mAh Integrated Battery,
                    Ultra Slim 8.9mm, FPC Antenna with Strong Signal, Phonebook Memory 1000 contacts.`,
      },
      {
        name: "Geo R25 Feature Phone - Green",
        image: "/assets/phone/PHOTO-2024-11-14-22-04-47.jpg",
        price: "2390",
        discount_price: "1950",
        specification: "Feature Phone",
        brand: "GEO PHONE",
        model: "R25",
        usb: "Type C",
        bluetooth_dialer: "Yes",
        fm_recording: "Yes",
        display: "2.4″ Inch Display",
        sim_slot: "2",
        dedicated_power_key: "Yes",
        dedicated_reset_key: "Yes",
        screen: "2.5D",
        processor: `MTK6261D`,
        camera: "",
        battery: "1200mAh Polymer Integrated",
        phonebook_memory: "",
        warranty: "1 Year",
        description: ` Experience simplicity with our feature phone. Designed for essential communication, 
        it offers reliable calling and texting functionality in a compact form.
        Stay connected effortlessly with its intuitive interface. With e-commerce integration, shop conveniently on the go. Embrace the ease of use and reliability of our feature phone for all your communication needs.`,
      },
      {
        name: "Smile M100Leo Dual Sim Feature Phone",
        image: "/assets/phone/PHOTO-2024-11-14-22-06-00.jpg",
        price: "1050",
        discount_price: "868",
        specification: "Feature Phone",
        brand: "Smile",
        model: "M100Leo",
        usb: "",
        bluetooth_dialer: "",
        fm_recording: "",
        display: "1.77 Inch Display",
        sim_slot: "",
        dedicated_power_key: "",
        dedicated_reset_key: "",
        screen: "",
        processor: ``,
        camera: "VGA",
        battery: "1100mAh",
        phonebook_memory: "",
        warranty: "1 Year",
        description: ` Experience simplicity with our feature phone. Designed for essential communication, 
        it offers reliable calling and texting functionality in a compact form.
        Stay connected effortlessly with its intuitive interface. With e-commerce integration, shop conveniently on the go. Embrace the ease of use and reliability of our feature phone for all your communication needs.`,
      },
      {
        name: "Jio J15 Max Dual SIM Feature Phone",
        image: "/assets/phone/PHOTO-2024-11-14-22-07-12.jpg",
        price: "1400",
        discount_price: "1102",
      },
      {
        name: "Smile Q9 Victory Smartphone - 3GB RAM - 32GB ROM - 13MP Camera - 6.6 Inch Display",
        image: "/assets/phone/PHOTO-2024-11-14-22-20-48.jpg",
        price: "4499",
        discount_price: "3195",
      },
      {
        name: "Vfone 10 Prime Smartphone - 6.3 Inch HD Display - 3GB RAM- 32GB ROM- 13MP Camera - Blue",
        image: "/assets/phone/PHOTO-2024-11-14-22-22-19.jpg",
        price: "9990",
        discount_price: "4990",
      },
      {
        name: "ZTE Blade V50 Design Smartphone - 8GB Ram - 256GB Rom - 13MP Camera - 6.6 Inch Display",
        image: "/assets/phone/PHOTO-2024-11-14-22-26-17.jpg",
        price: "15499",
        discount_price: "12999",
      },
      {
        name: "ZTE Nubia Neo Smartphone - 8GB Ram - 256GB Rom - 50MP Camera - 6.6 Inch Display",
        image: "/assets/phone/PHOTO-2024-11-14-22-28-11.jpg",
        price: "21499",
        discount_price: "18990",
      },
    ],
    watch: [
      {
        name: "Colmi C8 Max Nylon Mesh Touch Screen Smart Watch - Multicolor",
        image: "/assets/watch/PHOTO-2024-11-14-20-52-40.jpg",
        price: "5000",
        quantity: "10",
        discount_price: "",
        brand: "COLMI",
        product_type: "Smart Watch",
        dial_diameter: "",
        case_shape: "",
        band_width: "",
        band_lenght: "",
        clasp_type: "",
        water_resistance_depth: "",
        model: "C8 Max",
        screen_size: "1.93 inch IPS",
        touch_type: "Full screen touch",
        case_thickness: "12Mm",
        model: "C8 Max",
        screen_size: "1.93 inch IPS",
        touch_type: "Full screen touch",
        material: "Stainless Steel",
        band_material_type: "Stainless Steel",
        case_material: "Alloy",
        dial_display: "Digital",
        user: "Unisex",
        capatcity: "280mAh",
        bluetooth: "5.3V",
        compatibility: "Android 4.4 and above, iOS 8.0 and above, Harmony OS",
        description: `The Colmi C8 Max is a budget-friendly smartwatch with a 1.93-inch IPS LCD and a 280 mAh battery.
         It offers a variety of features, including heart rate and blood oxygen monitoring, sleep tracking, multiple sports modes, and Bluetooth calling.
          The watch is also water-resistant up to IP68, making it suitable for everyday use and light swimming.`,
      },
      {
        name: "Lige 411 Stainless Steel Touch Screen Sport Fitness Watche For Android iOS - Black",
        image: "/assets/watch/PHOTO-2024-11-14-20-54-47.jpg",
        price: "5000",
        quantity: "10",
        discount_price: "",
        brand: "Lige",
        product_type: "Watch",
        dial_diameter: "44Mm",
        case_shape: "Square",
        band_width: "20Mm",
        band_lenght: "22Cm",
        clasp_type: "Hidden Clasp",
        water_resistance_depth: "3Bar",
        case_thickness: "12Mm",
        model: "C8 Max",
        screen_size: "1.93 inch IPS",
        touch_type: "Full screen touch",
        material: "Stainless Steel",
        band_material_type: "Stainless Steel",
        case_material: "Alloy",
        dial_display: "Digital",
        user: "Unisex",
        capatcity: "",
        bluetooth: "",
        compatibility: "Android 4.4 and above, iOS 8.0 and above, Harmony OS",
        description: `The Lige 411 Stainless Steel Touch Screen Sport Fitness Watch for Android iOS in Black is a versatile and functional timepiece designed for active individuals.
                    This sporty watch features a sleek black design that adds a modern and stylish touch to your wrist.
                    The stainless steel construction ensures durability, while the touch screen interface allows for easy navigation and interaction with the watch's features.
                    Designed for compatibility with both Android and iOS devices, this watch offers convenient connectivity and synchronization with your smartphone.
                    It is equipped with fitness tracking features that can monitor your daily activities, including steps taken, distance traveled, and calories burned.
                    Additionally, the watch offers notifications for incoming calls, messages, and social media alerts, ensuring you stay connected while on the go. With its sporty and tech-savvy design,
                    the Lige 411 Stainless Steel Touch Screen Sport Fitness Watch in Black is a reliable companion for your active lifestyle and everyday use.`,
      },
      {
        name: "Lige 412 Stainless Steel Touch Screen Sport Fitness Watche For android iOS - Golden Chain",
        image: "/assets/watch/PHOTO-2024-11-14-20-57-58.jpg",
        price: "5000",
        discount_price: "",
      },
      {
        name: "Wavefun Aidig S smart Watch - Black",
        image: "/assets/watch/PHOTO-2024-11-14-21-00-24.jpg",
        price: "5000",
        discount_price: "",
      },
      {
        name: "CMF by Nothing Watch Pro Smart Watch - Dark Grey - NTG-WC",
        image: "/assets/watch/PHOTO-2024-11-14-21-59-40.jpg",
        price: "10999",
        discount_price: "7451",
      },
    ],
    earbuds: [
      {
        name: "Wavefun T200 TWS Wireless Earbuds - Black",
        image: "/assets/earbuds/PHOTO-2024-11-14-21-04-34.jpg",
        price: "5999",
        discount_price: "4427",
      },
      {
        name: "Remax RB-S2 Magnet Sports Earphone Bluetooth Headset - Black",
        image: "/assets/earbuds/PHOTO-2024-11-14-21-05-58.jpg",
        price: "5999",
        discount_price: "4427",
      },
      {
        name: "CMF by Nothing True Wireless Earbuds with Active Noise Cancellation - Orange - NTG-EBO",
        image: "/assets/earbuds/PHOTO-2024-11-14-21-56-04.jpg",
        price: "5999",
        discount_price: "4427",
      },
      {
        name: "CMF by Nothing True Wireless Earbuds with Active Noise Cancellation - Light Grey - NTG-EBL",
        image: "/assets/earbuds/PHOTO-2024-11-14-21-57-42.jpg",
        price: "5999",
        discount_price: "4427",
      },
      {
        name: "CMF by Nothing Neckband Pro With Active Noise Cancellation - Orange - NTG-NCo",
        image: "/assets/earbuds/PHOTO-2024-11-14-22-01-43.jpg",
        price: "3999",
        discount_price: "3509",
      },
    ],
    bag: [
      {
        name: "WILLIAMPOLO Synthetic Leather Slim 15.6 inch Laptop Backpack - Black",
        image: "/assets/bag/PHOTO-2024-11-14-22-10-21.jpg",
        price: "10000",
        discount_price: "6077",
      },
      {
        name: "Artic Hunter Oxford Backpack And Laptop Bag - Black",
        image: "/assets/bag/PHOTO-2024-11-14-22-10-21.jpg",
        price: "1790",
        discount_price: "720",
      },
      {
        name: "WiWU Macbook Mate Accessories Bag - Black",
        image: "/assets/bag/PHOTO-2024-11-14-22-13-21.jpg",
        price: "1700",
        discount_price: "1530",
      },
      
      {
        name: "WiWU Polyester Minimalist Travel Pouch Electronics Macbook Accessories Bag - Gray",
        image: "/assets/bag/PHOTO-2024-11-14-22-14-42.jpg",
        price: "1500",
        discount_price: "1305",
      },
    ],
    battery: [
      {
        name: "Kinyear Battery",
        image: "/assets/battery/PHOTO-2024-11-14-22-58-19.jpg",
        price: "14000",
        discount_price: "",
      },
    ],
    electric_tricycle: [
      {
        name: "Electric Tricycle",
        image: "/assets/electric_tricycle/PHOTO-2024-11-14-22-56-56.jpg",
        price: "160000",
        discount_price: "150000",
      },
    ],
    electronics: [
      {
        name: "Lenovo 60.96 cm (24 inch) Full HD VA Panel with 300 nits brightness, 95% sRGB Gaming Monitor",
        image: "/assets/electronic/PHOTO-2024-11-14-22-53-11.jpg",
        price: "50000",
        discount_price: "45000",
      },
    ],
  },
];
export default productDetails;
